org: muskanpareek
app: serverless-taskmaster-app
service: serverless-taskmaster-app


provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:619047314241:table/KaamKaro

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    KaamKaro:
     Type: AWS::DynamoDB::Table
     Properties:  
       TableName: KaamKaro
       BillingMode: PAY_PER_REQUEST
       AttributeDefinitions:
         - AttributeName: id
           AttributeType: S
       KeySchema:
          - AttributeName: id
            KeyType: HASH     
