org: muskanpareek
app: serverless-taskmaster-aws-app
service: serverless-taskmaster-app


provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: *
      Resource:
        - arn:aws:dynamodb:us-east-1:619047314241:table/KaamKaro


resources:
  Resources:
    KaamKaro:
     Type: AWS::DynamoDB::Table
     TableName: KaamKaro
     BillingMode: PAY_PER_REQUEST
     Properties:
       AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
       KeySchema:
        - AttributeName: id
           KeyType: HASH     
